[package]
name = "git-delorean"
version = "0.1.2"
edition = "2024"

[dependencies]
anyhow = "1.0"
ratatui = "0.26"
crossterm = "0.27"
syntect = { version = "5.2", default-features = false, features = ["default-fancy"] }
once_cell = "1.19"
unicode-width = "0.1"
